version: 1
policy:
  pullRequests: public
tasks:
  $let:
    event_str: {$json: {$eval: event}}
    scope_suffix:
      $if: 'tasks_for == "github-push"'
      then:
        $let:
          branch:
            $if: "event.ref[:11] == 'refs/heads/'"
            then: "${event.ref[11:]}"
        in: "branch:${branch}"
      else: "pull-request"
  in:
    - $if: '(tasks_for == "github-push" && event.ref in ["refs/heads/master", "refs/heads/epochs/daily", "refs/heads/epochs/weekly", "refs/heads/triggers/chrome_stable", "refs/heads/triggers/chrome_beta", "refs/heads/triggers/chrome_dev", "refs/heads/triggers/firefox_stable", "refs/heads/triggers/firefox_beta", "refs/heads/triggers/firefox_nightly"]) || tasks_for == "github-pull-request"'
      then:
        created: {$fromNow: ''}
        deadline: {$fromNow: '24 hours'}
        provisionerId: aws-provisioner-v1
        workerType:
          $if: event.repository.full_name == 'web-platform-tests/wpt'
          then:
            wpt-docker-worker
          else:
            github-worker
        metadata:
          name: "wpt Decision Task"
          description: "The task that creates all of the other tasks in the task graph"
          owner: ${event.pusher.email}
          source: ${event.repository.url}
        payload:
          image: harjgam/web-platform-tests:0.33
          maxRunTime: 7200
          artifacts:
            public/results:
              path: /home/test/artifacts
              type: directory
          command:
            - /bin/bash
            - --login
            - -c
            - set -ex;
              ~/start.sh
                ${event.repository.url}
                ${event.ref};
              cd ~/web-platform-tests;
              ./wpt decision
        scopes:
          - assume:repo:github.com/web-platform-tests/wpt:${scope_suffix}
        extra:
          github_event: "${event_str}"
